
trigger:
  branches:
    include:
    - main
    - releases/*
 paths:
    include:
    - apiProxy

pool:
  vmImage: 'ubuntu-latest'


steps:

- bash: |
    rm -rf /s
    ls
  enabled: "true"
  displayName: clean artifact 

- bash: |
    echo "azure pipeline first"
    echo "${BUILD_SOURCEVERSION:0:7}"

    mkdir Apigee_Proxy_log
    echo ${BUILD_SOURCEVERSION:0:7}-"failed" > Apigee_Proxy_log/pipeline_status
    echo "-----pwd------"
    pwd
    echo "------cat-----"
    cat Apigee_Proxy_log/pipeline_status
    echo "-----------"
  enabled: "true"
  displayName: echo 

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/Apigee_Proxy_log'
    artifact: 'Apigee_Proxy_Pipeline'
    publishLocation: 'pipeline'
