
trigger:
  branches:
    include:
    - main
    - releases/*

pool:
  vmImage: 'ubuntu-latest'


steps:

# Azure pipeline doest allow to change job working directory :(
# so... copy all apiProxy files to be able to keep GitHub repository organization 
- bash: |
    echo "azure pipeline first"
  enabled: "true"
  displayName: echo 

