
trigger:
  branches:
    include:
    - main
    - releases/*

pool:
  vmImage: 'ubuntu-latest'


steps:

# Azure pipeline doest allow to change job working directory :(
# so... copy all apiProxy files to be able to keep GitHub repository organization 
- bash: |
    echo "azure pipeline first"
    mkdir Apigee_Proxy
    echo "failed" > Apigee_Proxy/pipeline_status
    echo "-----------"
    cat Apigee_Proxy/pipeline_status
    echo "-----------"
  enabled: "true"
  displayName: echo 

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/Apigee_Proxy'
    artifact: 'Apigee_Proxy_Pipeline'
    publishLocation: 'pipeline'