
trigger:
  branches:
    include:
    - main
    - releases/*

pool:
  vmImage: 'ubuntu-latest'


steps:

# Azure pipeline doest allow to change job working directory :(
# so... copy all apiProxy files to be able to keep GitHub repository organization 
- bash: |
    echo "azure pipeline first"
    echo "myFile" > myFIle
  enabled: "true"
  displayName: echo 

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'myFile'
    publishLocation: 'pipeline'