# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java



trigger:
- main
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:


  API_VERSION: "googleapi"
  DEFAULT_APIGEE_ENV: "default-dev"
  DEFAULT_APIGEE_ORG: "bap-emea-apigee-5"

  TEST_HOST: 34.117.38.184.nip.io
  
  AUTHOR_EMAIL: $(APIGEE_USER)
  COMMIT_ID: $(Build.SourceVersion)
  COMMIT_BRANCH: $(Build.SourceBranch)

  # GCP_SERVICE_ACCOUNT, APIGEE_USER & APIGEE_PASSWORD are stored in Azure Pipeline variable settings
  
jobs:

- job: Apigee_Commit_Check
  timeoutInMinutes: 10
  steps:
  - bash: |
      echo "Job Apigee-Commit-Check"      
    enabled: "true"
    displayName: Apigee-Commit-Check-1


- job: Apigee_Proxy_Deploy
  timeoutInMinutes: 10
  dependsOn: Apigee_Commit_Check
  steps:
  - bash: |
        echo "Job Apigee-Proxy-Deploy"      
    enabled: "true"
    env:  
      DEFAULT_APIGEE_ORG: $(DEFAULT_APIGEE_ORG)
      DEFAULT_APIGEE_ENV: $(DEFAULT_APIGEE_ENV)
      COMMIT_BRANCH: $(COMMIT_BRANCH)


- job:  Apigee_Hub_Publish
  timeoutInMinutes: 10
  dependsOn: Apigee_Proxy_Deploy
  steps:
  - bash: |
      echo "Job Apigee-Hub-Publish"      
    enabled: "true"
    displayName:  Apigee-Hub-Publish-1

 
