resources:
  pipelines:
  - pipeline: azure-pipelines # Name of the pipeline resource.
    source: g-lalevee.Apigee-ApiHub-Simple-Azure-Pipeline # The name of the pipeline referenced by this pipeline resource.
    # project: xxxxx # Required only if the source pipeline is in another project
    trigger: true # Run apihub-pipeline when any run of apigee-pipeline completes

trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - apiHub

steps:
- bash: echo "API Hub publish runs first"