resources:
  pipelines:
  - pipeline: azure-pipelines # Name of the pipeline resource.
    source: g-lalevee.Apigee-Proxy # The name of the pipeline referenced by this pipeline resource.
    # project: xxxxx # Required only if the source pipeline is in another project
    trigger: true # Run apihub-pipeline when any run of apigee-pipeline completes

trigger:
  branches:
    include:
    - main
    - releases/*
#  paths:
#    include:
#    - apiHub

pool:
  vmImage: 'ubuntu-latest'


steps:

# Azure pipeline doest allow to change job working directory :(
# so... copy all apiProxy files to be able to keep GitHub repository organization 

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '97b846c9-c6db-4b04-90ec-3e4968d10843'
    definition: '6'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    allowFailedBuilds: true
    artifactName: 'Apigee_Proxy_Pipeline'
    targetPath: '$(Pipeline.Workspace)/s/Apigee_Proxy'

- bash: |
    echo "azure hub second --> " ${BUILD_SOURCEVERSION:0:7}
    ls
    echo "-----------"
    cat Apigee_Proxy_log/pipeline_status
    echo "-----------"
  enabled: "true"
  displayName: echo 

- bash: |
    rm -rf /s
    ls
  enabled: "true"
  displayName: clean artifact 
